config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rciam/rciam-federation-registry:
      branch: master
      repo: https://github.com/rciam/rciam-federation-registry.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-asparagus-camel.sh
        container: qc.acc_shabby-cyan-labradoodle
  QC.Doc:
    repos:
      github.com/rciam/rciam-federation-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-amethyst-chamois.sh
        container: qc.doc_flaky-eggplant-turtle
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-smalt-badger.sh
        container: qc.doc_snippy-cornflower-cattle
      github.com/rciam/rciam-federation-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-denim-bullfrog.sh
        container: qc.doc_flabby-jade-tetra
  QC.Lic:
    repos:
      github.com/rciam/rciam-federation-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-coral-chamois.sh
        container: qc.lic_wheezy-seashell-buzzard
  QC.Met:
    repos:
      github.com/rciam/rciam-federation-registry validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ultramarine-mayfly.sh
        container: qc.met_wheezy-blue-snake
  QC.Sty:
    repos:
      github.com/rciam/rciam-federation-registry jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-lavender-cougar.sh
        container: qc.sty_goopy-cinnamon-eagle
  QC.Ver:
    repos:
      github.com/rciam/rciam-federation-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-charcoal-whale.sh
        container: qc.ver_lousy-zucchini-lemur
timeout: 5400
