config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rciam/rciam-federation-registry:
      branch: master
      repo: https://github.com/rciam/rciam-federation-registry.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-charcoal-mongoose.sh
        container: qc.acc_surly-razzmatazz-civet
  QC.Doc:
    repos:
      github.com/rciam/rciam-federation-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-razzmatazz-ferret.sh
        container: qc.doc_tasty-denim-goat
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-viridian-chicken.sh
        container: qc.doc_sunny-turquoise-wildebeest
      github.com/rciam/rciam-federation-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-teal-salamander.sh
        container: qc.doc_lovely-peach-skunk
  QC.Lic:
    repos:
      github.com/rciam/rciam-federation-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-seashell-squirrel.sh
        container: qc.lic_skanky-pink-hamster
  QC.Met:
    repos:
      github.com/rciam/rciam-federation-registry validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-tiger.sh
        container: qc.met_thirsty-mauve-newfoundland
  QC.Sty:
    repos:
      github.com/rciam/rciam-federation-registry jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chocolate-ragdoll.sh
        container: qc.sty_muzzy-denim-iguana
  QC.Ver:
    repos:
      github.com/rciam/rciam-federation-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-myrtle-dugong.sh
        container: qc.ver_crappy-cream-uguisu
timeout: 5400
