config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rciam/rciam-federation-registry:
      branch: master
      repo: https://github.com/rciam/rciam-federation-registry.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-apricot-beaver.sh
        container: qc.acc_skimpy-black-ocelot
  QC.Doc:
    repos:
      github.com/rciam/rciam-federation-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-beige-blue.sh
        container: qc.doc_pasty-blue-opossum
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-firebrick-lobster.sh
        container: qc.doc_wiggy-chocolate-jaguar
      github.com/rciam/rciam-federation-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-stingray.sh
        container: qc.doc_skinny-periwinkle-lemur
  QC.Lic:
    repos:
      github.com/rciam/rciam-federation-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ochre-tetra.sh
        container: qc.lic_shaky-purple-dingo
  QC.Met:
    repos:
      github.com/rciam/rciam-federation-registry validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-tomato-moose.sh
        container: qc.met_woolly-purple-chicken
  QC.Sty:
    repos:
      github.com/rciam/rciam-federation-registry jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-chestnut-peccary.sh
        container: qc.sty_gloppy-cyan-chimpanzee
  QC.Ver:
    repos:
      github.com/rciam/rciam-federation-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-chartreuse-rat.sh
        container: qc.ver_paltry-aqua-oyster
timeout: 5400
