config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rciam/rciam-federation-registry:
      branch: master
      repo: https://github.com/rciam/rciam-federation-registry.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-copper-mayfly.sh
        container: qc.acc_pasty-pear-kudu
  QC.Doc:
    repos:
      github.com/rciam/rciam-federation-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-buff-hippopotamus.sh
        container: qc.doc_stinky-lemon-gopher
      github.com/rciam/rciam-federation-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-ivory-magpie.sh
        container: qc.doc_thirsty-wheat-worm
      github.com/rciam/rciam-federation-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cream-setter.sh
        container: qc.doc_lovely-tomato-shrew
  QC.Lic:
    repos:
      github.com/rciam/rciam-federation-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-salmon-mule.sh
        container: qc.lic_dorky-bistre-crane
  QC.Met:
    repos:
      github.com/rciam/rciam-federation-registry validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cerulean-vulture.sh
        container: qc.met_geeky-dandelion-toucan
  QC.Sty:
    repos:
      github.com/rciam/rciam-federation-registry jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-firebrick-nightingale.sh
        container: qc.sty_tasty-smalt-zonkey
  QC.Ver:
    repos:
      github.com/rciam/rciam-federation-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lavender-alligator.sh
        container: qc.ver_shaky-saffron-barracuda
timeout: 5400
